# Generated by Django 4.0 on 2021-12-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211101_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='color',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='variant',
            name='size',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
